// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Placeholder allowed for `prisma generate` when Railway has not injected DATABASE_URL yet.
    url: process.env["DATABASE_URL"] ?? "postgresql://build:build@127.0.0.1:5432/build",
  },
});
